export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  CHANGE_NAME_AND_NUMBER: "CHANGE_NAME_AND_NUMBER",
  SET_INITIAL_PRODUCT: "SET_INITIAL_PRODUCT",
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
}